---
- name: copy cluster config
  template:
    src: cluster-configuration.yaml.j2
    dest: /root/cluster-configuration.yaml 

- name: init first control plane node
  shell: |
    kubeadm init \
    {% if kube_replace_kubeproxy %}
      --skip-phases=addon/kube-proxy \
    {% endif %}
      --config /root/cluster-configuration.yaml \
      --upload-certs \
