---
- name: gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: create directory for ansible custom facts
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d

- name: set install kube fact
  ansible.builtin.template:
    src: kube.fact.j2
    dest: /etc/ansible/facts.d/kube.fact
  vars:
    joined: false
    cilium_installed: false

- name: re-read facts after adding kube fact
  ansible.builtin.setup:
    filter: ansible_local

- ansible.builtin.include: install-cri-o.yaml
  when: 
    - '"cri-o" not in ansible_facts.packages'
    - '"cri-o-runc" not in ansible_facts.packages'

- name: add kubernetes apt key
  ansible.builtin.apt_key: 
    url: '{{ kube_apt_key_url }}'
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: install kubernetes apt repository
  ansible.builtin.apt_repository: 
    repo: '{{ kube_apt_repository }}'

- name: check if kube_version is set
  ansible.builtin.fail:
    msg: kube_version not set
  when: kube_version is not defined

- name: install kubeadm kubectl kubelet and update apt cache 
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - kubeadm={{ kube_version }}-00
      - kubectl={{ kube_version }}-00
      - kubelet={{ kube_version }}-00

- name: hold kubeadm kubectl kubelet
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubeadm
    - kubectl
    - kubelet

- name: load br_netfilter 
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: enable ip forwarding 
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true

  # if the first master node has not joined the cluster
  # this indicates that we have a fresh cluster
- ansible.builtin.include: init-control-plane.yaml
  when:
    - inventory_hostname == groups.kube_master[0]
    - ansible_local.kube.joined == false

- ansible.builtin.include: generate-join-tokens.yaml
- ansible.builtin.include: generate-cert-key.yaml

- name: write KUBELET_EXTRA_ARGS
  ansible.builtin.lineinfile:
    path: '/etc/systemd/system/kubelet.service.d/10-kubeadm.conf'
    line: "{{ 'Environment=\"KUBELET_EXTRA_ARGS=' + kube_kubelet_extra_args + '\"' }}"
    regexp: '^Environment="KUBELET_EXTRA_ARGS='
    state: present
  register: config

- name: restart kubelet
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: kubelet
  when: config is changed

- ansible.builtin.include: join-control-plane.yaml
  when: 
    - inventory_hostname in groups.kube_master
    - ansible_local.kube.joined == false

- ansible.builtin.include: join-worker-node.yaml
  when: 
    - inventory_hostname in groups.kube_worker
    - ansible_local.kube.joined == false

- name: set and persist joined fact
  ansible.builtin.template:
    src: kube.fact.j2
    dest: /etc/ansible/facts.d/kube.fact
  vars:
    joined: true
    cilium_installed: '{{ ansible_local.kube.cilium_installed }}'
  when: ansible_local.kube.joined == false

- name: generate cilium config
  ansible.builtin.template:
    src: cilium.yaml.j2
    dest: /root/cilium.yaml
  when: 
    - inventory_hostname in groups.kube_master
    - ansible_local.kube.cilium_installed == false

- name: install cilium and wait for it to be ready  
  block:
    - name: install cilium
      shell: kubectl apply -f /root/cilium.yaml
    - name: wait for cilium to be ready
      shell: kubectl wait --timeout=5m --for=condition=ready -n kube-system -l k8s-app=cilium pod
  when: 
    - inventory_hostname == groups.kube_master[0]
    - ansible_local.kube.cilium_installed == false

- name: set and persist cilium_installed fact
  ansible.builtin.template:
    src: kube.fact.j2
    dest: /etc/ansible/facts.d/kube.fact
  vars:
    cilium_installed: true
    joined: true
  when: ansible_local.kube.cilium_installed == false
