---
- name: unhold kubeadm
  dpkg_selections:
    name: 'kubeadm'
    selection: install
  when: inventory_hostname == groups.kube_master[0]

- name: update kubeadm
  apt:
    update_cache: yes
    name: kubeadm={{ kube_version }}
  when: inventory_hostname == groups.kube_master[0]

- name: hold kubeadm
  dpkg_selections:
    name: 'kubeadm'
    selection: hold
  when: inventory_hostname == groups.kube_master[0]

- name: plan update
  shell: kubeadm upgrade plan
  when: inventory_hostname == groups.kube_master[0]

- name: apply upgrade
  shell: 'kubeadm upgrade apply v{{ kube_version.split("-")[0] }} -y'
  when: inventory_hostname == groups.kube_master[0]

- name: upgrade other control plane nodes
  include: upgrade-node.yaml
  when: inventory_hostname in groups.kube_master
  throttle: 1 # only do this node by node

- name: upgrade worker nodes
  include: upgrade-node.yaml
  when: inventory_hostname in groups.kube_worker
  throttle: 1 # same reason as above 










