---
- name: upgrade node
  ansible.builtin.shell: kubeadm upgrade node

- name: drain control plane node
  ansible.builtin.shell: 'kubectl drain {{ inventory_hostname }} --ignore-daemonsets'
  delegate_to: '{{ groups.kube_master[0] }}'

- name: unhold kubectl and kubelet
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: install
  loop:
    - kubectl
    - kubelet

- name: update kubectl and kubelet
  ansible.builtin.apt:
    pkg:
      - kubectl={{ kube_version }}
      - kubelet={{ kube_version }}

- name: hold kubectl and kubelet
  ansible.builtin.dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubectl
    - kubelet
    
- name: restart kubelet
  ansible.builtin.systemd:
    state: restarted   
    daemon_reload: true
    name: kubelet
    
- name: uncordon node
  ansible.builtin.shell: 'kubectl uncordon {{ inventory_hostname }}'
  delegate_to: '{{ groups.kube_master[0] }}'
