---
- name: upgrade node
  shell: kubeadm upgrade node

- name: drain control plane node
  shell: 'kubectl drain {{ inventory_hostname }} --ignore-daemonsets'

- name: unhold kubectl and kubelet
  dpkg_selections:
    name: '{{ item }}'
    selection: unhold
  loop:
    - kubectl
    - kubelet

- name: update kubectl and kubelet
  apt:
    pkg:
      - kubectl={{ kube_version }}
      - kubelet={{ kube_version }}

- name: hold kubectl and kubelet
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubectl
    - kubelet
    
- name: restart kubelet
  systemd:
    state: restarted   
    daemon_reload: true
    name: kubelet
    
- name: uncordon node
  shell: 'kubectl uncordon {{ inventory_hostname }}'
