---
- name: Converge
  hosts: all
  vars:
    ansible_user: root
    kube_oidc_auth_enabled: true
    kube_oidc_issuer_url: ""
    kube_oidc_client-id: ""
    kube_oidc_username_claim: ""
    kube_oidc_groups_claim: ""
  tasks:
    - name: "Include kubernetes-ansible"
      include_role:
        name: "kubernetes-ansible"
