---
- name: Converge
  hosts: all
  vars:
    ansible_user: root
    kube_version: 1.18.6-00
    kube_replace_kubeproxy: true
  tasks:
    - name: "Include kubernetes-ansible"
      include_role:
        name: "kubernetes-ansible"
