---
- name: Verify
  hosts: all
  tasks:
    - name: get cluster version
      shell: kubectl get nodes | grep "Ready" | wc -l
      register: check
      until: "check.stdout | int == 5"
      delegate_to: "{{ groups.kube_master[0] }}"
      delay: 2
      retries: 10



